"""Add APIKey relationship

Revision ID: 499fe9c0464b
Revises: 06eebc6747e8
Create Date: 2025-07-09 19:06:06.745479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '499fe9c0464b'
down_revision: Union[str, None] = '06eebc6747e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
