# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/proto/agent.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'src/proto/agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15src/proto/agent.proto\x12\x0cpixell.agent\"\x07\n\x05\x45mpty\">\n\x0cHealthStatus\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"\x8c\x01\n\x0c\x43\x61pabilities\x12\x0f\n\x07methods\x18\x01 \x03(\t\x12:\n\x08metadata\x18\x02 \x03(\x0b\x32(.pixell.agent.Capabilities.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"N\n\nA2AMessage\x12\x0f\n\x07jsonrpc\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\x0e\n\x06method\x18\x03 \x01(\t\x12\x13\n\x0bparams_json\x18\x04 \x01(\t\"\xd6\x01\n\rActionRequest\x12-\n\x0b\x61\x32\x61_message\x18\x01 \x01(\x0b\x32\x18.pixell.agent.A2AMessage\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12?\n\nparameters\x18\x03 \x03(\x0b\x32+.pixell.agent.ActionRequest.ParametersEntry\x12\x12\n\nrequest_id\x18\x04 \x01(\t\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xd4\x01\n\x0c\x41\x63tionResult\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06result\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12\x12\n\nrequest_id\x18\x04 \x01(\t\x12\x13\n\x0b\x64uration_ms\x18\x05 \x01(\x03\x12:\n\x08metadata\x18\x06 \x03(\x0b\x32(.pixell.agent.ActionResult.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"*\n\x04Pong\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x32\x86\x02\n\x0c\x41gentService\x12\x39\n\x06Health\x12\x13.pixell.agent.Empty\x1a\x1a.pixell.agent.HealthStatus\x12G\n\x14\x44\x65scribeCapabilities\x12\x13.pixell.agent.Empty\x1a\x1a.pixell.agent.Capabilities\x12\x41\n\x06Invoke\x12\x1b.pixell.agent.ActionRequest\x1a\x1a.pixell.agent.ActionResult\x12/\n\x04Ping\x12\x13.pixell.agent.Empty\x1a\x12.pixell.agent.Pongb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.proto.agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CAPABILITIES_METADATAENTRY']._loaded_options = None
  _globals['_CAPABILITIES_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_ACTIONREQUEST_PARAMETERSENTRY']._loaded_options = None
  _globals['_ACTIONREQUEST_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_ACTIONRESULT_METADATAENTRY']._loaded_options = None
  _globals['_ACTIONRESULT_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_EMPTY']._serialized_start=39
  _globals['_EMPTY']._serialized_end=46
  _globals['_HEALTHSTATUS']._serialized_start=48
  _globals['_HEALTHSTATUS']._serialized_end=110
  _globals['_CAPABILITIES']._serialized_start=113
  _globals['_CAPABILITIES']._serialized_end=253
  _globals['_CAPABILITIES_METADATAENTRY']._serialized_start=206
  _globals['_CAPABILITIES_METADATAENTRY']._serialized_end=253
  _globals['_A2AMESSAGE']._serialized_start=255
  _globals['_A2AMESSAGE']._serialized_end=333
  _globals['_ACTIONREQUEST']._serialized_start=336
  _globals['_ACTIONREQUEST']._serialized_end=550
  _globals['_ACTIONREQUEST_PARAMETERSENTRY']._serialized_start=501
  _globals['_ACTIONREQUEST_PARAMETERSENTRY']._serialized_end=550
  _globals['_ACTIONRESULT']._serialized_start=553
  _globals['_ACTIONRESULT']._serialized_end=765
  _globals['_ACTIONRESULT_METADATAENTRY']._serialized_start=206
  _globals['_ACTIONRESULT_METADATAENTRY']._serialized_end=253
  _globals['_PONG']._serialized_start=767
  _globals['_PONG']._serialized_end=809
  _globals['_AGENTSERVICE']._serialized_start=812
  _globals['_AGENTSERVICE']._serialized_end=1074
# @@protoc_insertion_point(module_scope)
