name: test_no_db

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools wheel pip-tools
        # Try with timeout and backtracking limit to prevent resolution-too-deep
        pip install -r requirements.txt --timeout 300 || \
        pip install -r requirements.txt --use-deprecated=legacy-resolver || \
        (pip install --no-deps -r requirements.txt && pip check)
    
    - name: Run core tests (no database)
      run: |
        python test_no_db.py
    
    - name: Run pytest tests
      run: |
        pytest -v --tb=short
      continue-on-error: true  # pytest may fail if no test files found
    
    - name: Run linting
      run: |
        flake8 app/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 app/ --count --max-complexity=10 --max-line-length=100 --statistics
      continue-on-error: true
    
    - name: Run type checking
      run: |
        mypy app/ --ignore-missing-imports
      continue-on-error: true
